version: 2.1
orbs:
  node: circleci/heroku@x.y
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
 workflows:
   heroku_deploy:
     jobs:
       - build
       - heroku/deploy-via-git
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master

