version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
              name: Install JUnit coverage reporter
              command: yarn add --dev jest-junit
            - run:
                name: Run tests with JUnit as reporter
                command: jest --ci --runInBand --reporters=default --reporters=jest-junit
                environment:
                  JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
            - run: npm run test:e2e
            - run: npm run test:cov
workflows:
  build-and-test:
    jobs:
      - build-and-test
